### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by skornel02** [mskv/valid-ts#12]
I want to ask about the legal part of this repository.
The [npm repository](https://www.npmjs.com/package/valid-ts) says this is MIT licensed, but the repository is currently unlicensed.
Could you please clarify the licensing?

**Comment by mskv** [comment]
Thanks for letting me know, I will sort things out this evening.

**Comment by mskv** [comment]
@skornel02 Thanks again. Should be fixed now. Closing the issue, please feel free to reopen if you spot any problems.
